apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: seattle
  labels:
    role: webserver
  annotations:
    configmanagement.gke.io/cluster-selector: select-cloud-google
spec:
  replicas: 2
  selector:
    matchLabels:
      role: webserver
  template:
    metadata:
      labels:
        role: webserver
    spec:
      containers:
      - name: frontend
        image: nbrand/seattle-nginx
        ports:
        - containerPort: 80
