apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: gke
    # configmanagement.gke.io/cluster-selector: select-cloud-google
  name: apache-deployment
  namespace: apache
  labels:
    role: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      role: webserver
  template:
    metadata:
      labels:
        role: webserver
    spec:
      containers:
      - name: frontend
        image: httpd
        ports:
        - containerPort: 80
